export default {
  RECEIVE_TOKEN: 'RECEIVE_TOKEN',
  START_REQUEST: 'START_REQUEST',
  COMPLETE_REQUEST: 'COMPLETE_REQUEST',
  RECEIVE_CURRENT_USER: 'RECEIVE_CURRENT_USER',
  TOKEN_DELETED: 'TOKEN_DELETED',
}
